// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aycjzixhdarwgzdwoxun.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF5Y2p6aXhoZGFyd2d6ZHdveHVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4ODE5MTQsImV4cCI6MjA2MDQ1NzkxNH0.6jA4mk5ozJsZSEKdIuN6hq8bZVWWPic2GPNfZSArG7c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);